def get_capital(state):
    # Mapping of full state names to capitals
    capitals = {
        "alabama": "Montgomery",
        "alaska": "Juneau",
        "arizona": "Phoenix",
        "arkansas": "Little Rock",
        "california": "Sacramento",
        "colorado": "Denver",
        "connecticut": "Hartford",
        "delaware": "Dover",
        "florida": "Tallahassee",
        "georgia": "Atlanta",
        "hawaii": "Honolulu",
        "idaho": "Boise",
        "illinois": "Springfield",
        "indiana": "Indianapolis",
        "iowa": "Des Moines",
        "kansas": "Topeka",
        "kentucky": "Frankfort",
        "louisiana": "Baton Rouge",
        "maine": "Augusta",
        "maryland": "Annapolis",
        "massachusetts": "Boston",
        "michigan": "Lansing",
        "minnesota": "St. Paul",
        "mississippi": "Jackson",
        "missouri": "Jefferson City",
        "montana": "Helena",
        "nebraska": "Lincoln",
        "nevada": "Carson City",
        "new hampshire": "Concord",
        "new jersey": "Trenton",
        "new mexico": "Santa Fe",
        "new york": "Albany",
        "north carolina": "Raleigh",
        "north dakota": "Bismarck",
        "ohio": "Columbus",
        "oklahoma": "Oklahoma City",
        "oregon": "Salem",
        "pennsylvania": "Harrisburg",
        "rhode island": "Providence",
        "south carolina": "Columbia",
        "south dakota": "Pierre",
        "tennessee": "Nashville",
        "texas": "Austin",
        "utah": "Salt Lake City",
        "vermont": "Montpelier",
        "virginia": "Richmond",
        "washington": "Olympia",
        "west virginia": "Charleston",
        "wisconsin": "Madison",
        "wyoming": "Cheyenne"
    }

    # Mapping of abbreviations to full state names
    abbreviations = {
        "al": "alabama",
        "ak": "alaska",
        "az": "arizona",
        "ar": "arkansas",
        "ca": "california",
        "co": "colorado",
        "ct": "connecticut",
        "de": "delaware",
        "fl": "florida",
        "ga": "georgia",
        "hi": "hawaii",
        "id": "idaho",
        "il": "illinois",
        "in": "indiana",
        "ia": "iowa",
        "ks": "kansas",
        "ky": "kentucky",
        "la": "louisiana",
        "me": "maine",
        "md": "maryland",
        "ma": "massachusetts",
        "mi": "michigan",
        "mn": "minnesota",
        "ms": "mississippi",
        "mo": "missouri",
        "mt": "montana",
        "ne": "nebraska",
        "nv": "nevada",
        "nh": "new hampshire",
        "nj": "new jersey",
        "nm": "new mexico",
        "ny": "new york",
        "nc": "north carolina",
        "nd": "north dakota",
        "oh": "ohio",
        "ok": "oklahoma",
        "or": "oregon",
        "pa": "pennsylvania",
        "ri": "rhode island",
        "sc": "south carolina",
        "sd": "south dakota",
        "tn": "tennessee",
        "tx": "texas",
        "ut": "utah",
        "vt": "vermont",
        "va": "virginia",
        "wa": "washington",
        "wv": "west virginia",
        "wi": "wisconsin",
        "wy": "wyoming"
    }

    key = state.lower()

    # If it's an abbreviation, convert to full state name
    if key in abbreviations:
        key = abbreviations[key]

    return capitals.get(key, "Unknown state")
